# Generated by Django 5.2.14 on 2026-05-19 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chat_user_alter_chat_id_alter_message_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='chat',
            new_name='user',
        ),
    ]
