# Generated by Django 5.2.14 on 2026-05-19 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_rename_chat_message_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='user',
            new_name='chat',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='user',
        ),
        migrations.AlterField(
            model_name='message',
            name='role',
            field=models.CharField(max_length=20),
        ),
    ]
